# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: internal/controllers/grpc/protos/post_v1.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    "",
    "internal/controllers/grpc/protos/post_v1.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n.internal/controllers/grpc/protos/post_v1.proto";\n\x11\x43reatePostRequest\x12\x14\n\x0ctext_content\x18\x01 \x01(\t\x12\x10\n\x08owner_id\x18\x02 \x01(\t" \n\x12\x43reatePostResponse\x12\n\n\x02id\x18\x01 \x01(\t" \n\x12GetPostByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t"_\n\x13GetPostByIdResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0ctext_content\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\t\x12\x12\n\nupdated_at\x18\x04 \x01(\t2u\n\x06PostV1\x12\x33\n\x06\x43reate\x12\x12.CreatePostRequest\x1a\x13.CreatePostResponse"\x00\x12\x36\n\x07GetById\x12\x13.GetPostByIdRequest\x1a\x14.GetPostByIdResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "internal.controllers.grpc.protos.post_v1_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CREATEPOSTREQUEST"]._serialized_start = 50
    _globals["_CREATEPOSTREQUEST"]._serialized_end = 109
    _globals["_CREATEPOSTRESPONSE"]._serialized_start = 111
    _globals["_CREATEPOSTRESPONSE"]._serialized_end = 143
    _globals["_GETPOSTBYIDREQUEST"]._serialized_start = 145
    _globals["_GETPOSTBYIDREQUEST"]._serialized_end = 177
    _globals["_GETPOSTBYIDRESPONSE"]._serialized_start = 179
    _globals["_GETPOSTBYIDRESPONSE"]._serialized_end = 274
    _globals["_POSTV1"]._serialized_start = 276
    _globals["_POSTV1"]._serialized_end = 393
# @@protoc_insertion_point(module_scope)
