# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import warnings

import grpc

from internal.controllers.grpc.protos import (
    post_v1_pb2 as internal_dot_controllers_dot_grpc_dot_protos_dot_post__v1__pb2,
)

GRPC_GENERATED_VERSION = "1.73.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in internal/controllers/grpc/protos/post_v1_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class PostV1Stub(object):
    """Defines a package for the protocol buffer messages to prevent name clashes.
    It's good practice to include a version number (e.g., v1).

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
            "/PostV1/Create",
            request_serializer=internal_dot_controllers_dot_grpc_dot_protos_dot_post__v1__pb2.CreatePostRequest.SerializeToString,
            response_deserializer=internal_dot_controllers_dot_grpc_dot_protos_dot_post__v1__pb2.CreatePostResponse.FromString,
            _registered_method=True,
        )
        self.GetById = channel.unary_unary(
            "/PostV1/GetById",
            request_serializer=internal_dot_controllers_dot_grpc_dot_protos_dot_post__v1__pb2.GetPostByIdRequest.SerializeToString,
            response_deserializer=internal_dot_controllers_dot_grpc_dot_protos_dot_post__v1__pb2.GetPostByIdResponse.FromString,
            _registered_method=True,
        )


class PostV1Servicer(object):
    """Defines a package for the protocol buffer messages to prevent name clashes.
    It's good practice to include a version number (e.g., v1).

    """

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_PostV1Servicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Create": grpc.unary_unary_rpc_method_handler(
            servicer.Create,
            request_deserializer=internal_dot_controllers_dot_grpc_dot_protos_dot_post__v1__pb2.CreatePostRequest.FromString,
            response_serializer=internal_dot_controllers_dot_grpc_dot_protos_dot_post__v1__pb2.CreatePostResponse.SerializeToString,
        ),
        "GetById": grpc.unary_unary_rpc_method_handler(
            servicer.GetById,
            request_deserializer=internal_dot_controllers_dot_grpc_dot_protos_dot_post__v1__pb2.GetPostByIdRequest.FromString,
            response_serializer=internal_dot_controllers_dot_grpc_dot_protos_dot_post__v1__pb2.GetPostByIdResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "PostV1", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("PostV1", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class PostV1(object):
    """Defines a package for the protocol buffer messages to prevent name clashes.
    It's good practice to include a version number (e.g., v1).

    """

    @staticmethod
    def Create(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/PostV1/Create",
            internal_dot_controllers_dot_grpc_dot_protos_dot_post__v1__pb2.CreatePostRequest.SerializeToString,
            internal_dot_controllers_dot_grpc_dot_protos_dot_post__v1__pb2.CreatePostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetById(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/PostV1/GetById",
            internal_dot_controllers_dot_grpc_dot_protos_dot_post__v1__pb2.GetPostByIdRequest.SerializeToString,
            internal_dot_controllers_dot_grpc_dot_protos_dot_post__v1__pb2.GetPostByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
